import Link from "next/link";
import React from "react";
import User from "./User";
import { Metadata } from "next";

export const metadata: Metadata = {
	title: "Next JS - Users",
	description: "Generated by create next app",
};

const page: React.FC = async () => {
	const res = await fetch("http://localhost:3000/user");
	const data = await res.json();
	console.log(data);


	return (
		<div>
			<h1>Users{" ' "} page</h1>

			<ul className="flex flex-wrap">
				{data.map((user: any) => (
					<User key={user.id} user={user} />
				))}
			</ul>
		</div>
	);
};

export default page;
