import { Metadata } from "next";
import React from "react";
import Link from "next/link";

export const metadata: Metadata = {
	title: "Next JS - About us",
	description: "Generated by create next app",
};

const page: React.FC = () => {
	return (
		// full-bleed background but centered content so layout/header stays intact
		<section className="w-full bg-[#C9DDEE]">
			<div className="mx-auto max-w-6xl px-4 py-16">
				<div className="bg-white rounded-2xl shadow-lg overflow-hidden md:flex">
					{/* Text column */}
					<div className="md:w-1/2 p-8 bg-[#C9DDEE]">
						<h1 className="text-3xl font-extrabold text-[#27568B] mb-4">О нас</h1>
						<p className="text-[#27568B]/90 mb-6">
							Добро пожаловать в наш блог — здесь мы делимся идеями, опытом и
							практическими руководствами по разработке. Наша цель — делать
							понятные и полезные материалы, которые помогут вам создавать
							качественные проекты.
						</p>

						<ul className="mb-6 space-y-3 text-[#27568B]/90">
							<li>• Глубокие статьи и гайды</li>
							<li>• Примеры кода и разборы</li>
							<li>• Практические советы и шаблоны</li>
						</ul>

						<div className="flex flex-wrap gap-3">
							<Link
								href="/blog"
								className="inline-block px-4 py-2 rounded-md bg-[#27568B] text-[#C9DDEE] hover:bg-[#47A1C4] transition"
							>
								Читать блог
							</Link>

							<Link
								href="/contact"
								className="inline-block px-4 py-2 rounded-md bg-[#B68250] text-white hover:opacity-95 transition"
							>
								Связаться
							</Link>
						</div>
					</div>

					{/* Graphic column */}
					<div className="md:w-1/2 p-8 flex items-center justify-center" style={{ backgroundColor: '#F8FBFF' }}>
						<div
							className="w-56 h-56 rounded-full flex items-center justify-center text-white text-3xl font-bold"
							style={{ background: 'linear-gradient(135deg,#47A1C4 0%, #27568B 100%)' }}
						>
							B
						</div>
					</div>
				</div>
			</div>
		</section>
	);
};

export default page;
