import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import AuthProvider from "@/components/AuthProvider";
import AuthComponent from "@/components/AuthComponent";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Next JS",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<AuthProvider>
				<body
					className={`${geistSans.variable} ${geistMono.variable} bg-[#a8cedd] antialiased`}
				>
					<header className="w-full border-b bg-[#C9DDEE] py-4 shadow-sm">
						<div className="mx-auto flex w-full max-w-6xl items-center justify-between px-4">
							<Link href="/" className="flex items-center gap-3">
								<div className="flex items-center justify-center w-10 h-10 rounded-md bg-[#27568B] text-[#C9DDEE] font-bold">B</div>
								<span className="text-xl font-semibold text-[#27568B]">My Blog</span>
							</Link>
							<nav className="hidden md:flex items-center gap-6">
								<Link href="/" className="text-[#27568B] hover:text-[#47A1C4] transition-colors">Home</Link>
								<Link href="/about" className="text-[#27568B] hover:text-[#47A1C4] transition-colors">About</Link>
								<Link href="/blog" className="text-[#27568B] hover:text-[#47A1C4] transition-colors">Blog</Link>
								<Link href="/contact" className="text-[#27568B] hover:text-[#47A1C4] transition-colors">Contact</Link>
							</nav>

							<div className="flex items-center gap-4">
								<button className="md:hidden p-2 rounded-md hover:bg-[#C9DDEE]/60">
									<svg className="w-6 h-6 text-[#27568B]" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
										<path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 12h16M4 18h16" />
									</svg>
								</button>

								<div>
									<Link href="/profile">
									<AuthComponent />
									</Link>
								</div>
							</div>
						</div>
					</header>

					<main className="min-h-screen w-full px-4 py-6 mx-auto max-w-5xl">
						{children}
					</main>

					<footer className="w-full border-t bg-[#C9DDEE] py-4 mt-10">
						<div className="mx-auto max-w-5xl px-4 text-center text-sm text-gray-600">
							© 2025 My App. All rights reserved.
						</div>
					</footer>
				</body>
			</AuthProvider>
		</html>
	);
}
