import { Metadata } from "next";
import Link from "next/link";
import prisma from "@/lib/prisma";

export const metadata: Metadata = {
	title: "Next JS - Home",
	description: "Generated by create next app",
};

type PostItem = {
	id: number;
	title: string;
	content?: string | null;
	author: { name?: string | null } | null;
};

async function getPosts(): Promise<PostItem[]> {
	try {
		const posts = await prisma.post.findMany({
			where: { published: true },
			include: { author: true },
			orderBy: { id: "desc" },
			take: 6,
		});

		return posts.map((p) => ({
			id: p.id,
			title: p.title,
			content: p.content,
			author: p.author ? { name: p.author.name } : null,
		}));
	} catch (e) {
		return [
			{ id: 1, title: "Как начать с Next.js", content: "Краткое руководство по началу работы.", author: { name: "Admin" } },
			{ id: 2, title: "Полезные утилиты для разработчика", content: "Список утилит и настроек.", author: { name: "Editor" } },
		];
	}
}

export default async function Home() {
	const posts = await getPosts();

	return (
		<main className="w-full">
			{/* Hero */}
			<section className="w-full bg-[#47A1C4] rounded-3xl ">
				<div className="mx-auto max-w-6xl px-4 py-20 text-center">
					<h1 className="text-5xl font-extrabold text-white mb-4">Добро пожаловать в наш блог</h1>
					<p className="text-lg text-white/90 max-w-2xl mx-auto">
						Мы публикуем статьи, гайды и полезные материалы по веб-разработке.
						Читайте, учитесь и развивайтесь вместе с нами.
					</p>
					<div className="mt-8 flex justify-center gap-4">
						<Link href="/blog" className="px-5 py-3 rounded-md bg-[#27568B] text-[#C9DDEE] hover:bg-[#234b74] transition">
							Смотреть все посты
						</Link>
						<Link href="/about" className="px-5 py-3 rounded-md bg-[#B68250] text-white hover:opacity-95 transition">
							О нас
						</Link>
					</div>
				</div>
			</section>

			{/* Posts grid */}
			<section className="mx-auto max-w-6xl px-4 py-16">
				<h2 className="text-2xl font-bold text-[#27568B] mb-6">Последние публикации</h2>

				<div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
					{posts.map((post) => (
						<article key={post.id} className="bg-white rounded-lg shadow-md overflow-hidden">
							<div className="p-6">
								<h3 className="text-lg font-semibold text-[#27568B] mb-2 truncate">{post.title}</h3>
								<p className="text-sm text-[#27568B]/80 mb-4 h-16 overflow-hidden">{post.content ?? "Краткое описание отсутствует."}</p>
								<div className="flex items-center justify-between">
									<div className="text-xs text-[#27568B]/80">{post.author?.name ?? "Автор"}</div>
									<Link href={`/blog/posts/${post.id}`} className="text-sm text-[#47A1C4] hover:text-[#27568B]">
										Читать
									</Link>
								</div>
							</div>
						</article>
					))}
				</div>
			</section>
		</main>
	);
}
